import Link from "next/link";
import Head from "next/head";
import { BsArrowUpRight } from "react-icons/bs";

type Props = {
  route: string;
  text: string;
  bgColor: string;
  arrowBgColor: string;
};

const AuthButtons = (props: Props) => {
  return (
    <Link
      href={props.route}
      className={`${props.bgColor} border-[1px] rounded-full flex items-center px-4 py-2`}
    >
      <button className="flex justify-center items-center mx-auto gap-5">
        {props.text}
        <div
          className={`${props.arrowBgColor} rounded-full w-[30px] h-[30px] items-center flex justify-end p-[7px]`}
        >
          <BsArrowUpRight className="w-5 h-5 mx-auto flex" />
        </div>
      </button>
    </Link>
  );
};

const LargeAuthButtons = (props: Props) => {
  return (
    <Link
      href={props.route}
      className={`${props.bgColor} border-[1px] flex w-auto px-8 h-[60px] rounded-[50px]`}
    >
      <button className="flex justify-center items-center mx-auto gap-3 sm:gap-5">
        {props.text}

        <div
          className={`${props.arrowBgColor} rounded-full w-[40px] h-[40px] items-center flex justify-end`}
        >
          <BsArrowUpRight className="w-5 h-5  mx-auto flex" />
        </div>
      </button>
    </Link>
  );
};

const HeroBanner = () => {
  return (
    // font-dmSans
    <div>
      <div className="">
        <Head>
          <title>ThirdSpace </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/Logo.svg" />
        </Head>

        {/* Desktop View */}

        <div className="hidden md:flex flex-col">
          <h1 className="text-center font-extrabold xl:text-8xl mx-24 lg:text-6xl md:text-5xl items-center justify-center mt-40 dark:white ">
            All-in-one Workspace for
            {/* <span className="bg-gradient-to-r from-[#02EC88] to-[#5CB25D] inline-block text-transparent bg-clip-text">
              Git
            </span> */}
            <br />{" "}
            <p className="bg-gradient-to-r from-[#02EC88] to-[#5CB25D] inline-block text-transparent bg-clip-text mt-6">
              Remote Teams
            </p>
          </h1>

          <div className="text-center mt-10 lg:mx-8 xl:mx-8 md:mx-6">
            <p className="max-w-[700px] mx-auto text-lg md:text-xl leading-7">
              We&apos;re not just another tool; we&apos;re your all-in-one
              solution for streamlined remote collaboration
            </p>
            {/* <p className=""> blockchain-powered Payrolls, outsource tasks 
            and chat system  with A.I workspace assistant</p> */}
          </div>

          {/* <div className="text-white flex flex-col md:flex-row gap-10 justify-center mt-10">
              <LargeAuthButtons
                route={"/signin"}
                text={"Sign In"}
                bgColor={"bg-[#1F1F1F]"}
                arrowBgColor={"bg-[#26D577]"}
              />

              <LargeAuthButtons
                route={"/signup"}
                text={"Sign Up"}
                bgColor={"bg-[#26D577]"}
                arrowBgColor={"bg-[#1F1F1F]"}
              />
            </div> */}
        </div>

        {/* Mobile View */}
        <div className="flex flex-col md:hidden ">
          <h1 className="text-center font-extrabold text-3xl sm:text-5xl items-center justify-center mt-20 leading-[40px] text-black dark:text-white ">
            All-in-one Workspace for
            <br /> <span className="text-[#26D577] mt-2">Remote Teams</span>
          </h1>

          <div className="text-center leading-7 font-normal mt-4 text-sm sm:text-lg px-1">
            We&apos;re not just another tool; we&apos;re your all-in-one
            solution for streamlined remote collaboration
          </div>

          {/* <div className="flex text-white flex-row gap-4 justify-center mt-12">
            <AuthButtons
              text={"Sign In"}
              route={"/signin"}
              bgColor={"bg-[#1F1F1F]"}
              arrowBgColor={"bg-[#26D577]"}
            />

            <AuthButtons
              text={"Sign up"}
              route={"/signup"}
              bgColor={"bg-[#26D577]"}
              arrowBgColor={"bg-[#1F1F1F]"}
            />
          </div> */}
        </div>
      </div>
    </div>
  );
};

export default HeroBanner;
