import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/nav/navbar";
import Provider from "@/components/theme/theme-provider";

export const metadata: Metadata = {
  title: "Syncteam - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Provider>
          <>
            <Header />
            {children}
            <Footer />
          </>
        </Provider>
      </body>
    </html>
  );
}
